### ISSUE TITLE
Show user's image & Name in public profile link

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-app#106]
The public profile URL doesn't have proper meta tags which show an image of the user & name while sharing on social media.

Try sharing your public profile page on WhatsApp or Telegram to test the link

**Comment by Eshaabhasin** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by xlogix** [comment]
Assigned!

**Comment by shreyakapoor08** [comment]
can i work on this issue?

**Comment by xlogix** [comment]
Assigned!
