### ISSUE TITLE
Implement Proper Search Query

### ISSUE THREAD

**Issue by R3l3ntl3ss** [fnplus/footsteps-app#11]
Need to implement the right Graphql query to search through all the learning paths and footsteps. Right now I am using the contains clause but it requires the user to be very specific with the keyword or else it doesn't work. 

Do we need to create a [custom function](https://docs.hasura.io/1.0/graphql/manual/queries/custom-functions.html)?

**Comment by krsnvijay** [comment]
https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html

Use _like for string pattern matching similar to SQL

**Comment by R3l3ntl3ss** [comment]
Cool! I used "%query%" and _ilike and it works great.
