### ISSUE TITLE
No image in About Footseps section

### ISSUE THREAD

**Issue by ramneek008** [fnplus/footsteps-app#154]
**Describe the bug**
No image is visible in the About Footseps section. The borders are created but no image inside.

**To Reproduce**
1. Go to 'main page'
2. Scroll down to 'About Footseps'
3. See error

**Expected behavior**
The image should be available in the box

**Screenshots**
![download (1)](https://user-images.githubusercontent.com/48586823/81843760-b04b8500-956b-11ea-82db-2e511807cb71.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by ramneek008** [comment]
I would like to work on this issue. Please assign me

**Comment by xlogix** [comment]
Sure, go ahead!
