### ISSUE TITLE
Add ability to make paths private

### ISSUE THREAD

**Issue by R3l3ntl3ss** [fnplus/footsteps-app#16]
The feature should be available while creating as well as editing the path.

**Comment by prajwal714** [comment]
Can you please describe the feature briefly @R3l3ntl3ss @xlogix . Thanks

**Comment by xlogix** [comment]
@prajwal714 So, we want the users to have the ability to keep their learning paths private if needed. The user can make the path private by a 'switch' on the learning path itself and the path along with thee 'footsteps' would not be visible in search results and the user's public profile.

**Comment by prajwal714** [comment]
okay sure @xlogix I'll work on this and get back to you in case of queries.

**Comment by prajwal714** [comment]
Added the Private Switch in both add and Edit pages, updated the location, also updated the queries (Added the field isPrivate) Kindly review @xlogix @R3l3ntl3ss . Thanks
![Screenshot from 2020-03-03 19-47-23](https://user-images.githubusercontent.com/30700921/75784467-3b4c1a00-5d88-11ea-8a14-cd7cb2267eeb.png)
![Screenshot from 2020-03-03 19-47-42](https://user-images.githubusercontent.com/30700921/75784496-456e1880-5d88-11ea-91b8-7f9ce47298eb.png)

**Comment by xlogix** [comment]
There's some padding on the left side of the Private Label. Can it be aligned?

It's my OCD.

**Comment by prajwal714** [comment]
Done!!
