### ISSUE TITLE
Why Sign In Made Mandatory --- 

### ISSUE THREAD

**Issue by surapuramakhil** [fnplus/footsteps-app#22]
why this app/web make sign in compulsory? 

it will cause privacy concerns of activity tracking. If they don't require to.

PS: most people won't like to try due to privacy concerns. Just a bit of Advice of what i feel.

**Comment by xlogix** [comment]
Hi Akhil, sign-in is necessary to upvote/share your own learning paths. A crowdsourced app does need individuals to confirm their identity. Also, we're asking the most basic form of authentication. It isn't anything more than your name and email-id.
