### ISSUE TITLE
Add a contribution guidelines

### ISSUE THREAD

**Issue by Adnank122** [fnplus/footsteps-app#23]
Hi, 
I would like to propose that a contribution guidelines document should be added to the repo to make it easy for the contributors like me to get started with the projects. What I'm proposing is a standard way of making PRs, branch naming, commit messages and anything else that I might be missing. 

I was searching around and I found this [guide](https://github.com/ahmadawais/Emoji-Log/blob/master/README.md) for making the commit messages standard. Any help, guidelines would be appreciated and I'm willing to make a document based on the suggestions.

**Comment by xlogix** [comment]
We can go with the standard guidelines like making a new branch while proposing a new feature, we can add a checklist related to the pull request etc.

**Comment by abhinashgiri** [comment]
May I work on this as part of GSSOC 20?

**Comment by xlogix** [comment]
Sure! Go ahead

**Comment by abhinashgiri** [comment]
Sir, please assign it to me.

**Comment by xlogix** [comment]
Assigned!
