### ISSUE TITLE
Modify the Home Page

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-app#25]
The home page of the app can be modified to include the learning paths which the user has subscribed to/starred/active on. It can also include recommendations for other paths based on user's preferences/active learning paths. 

This would work well with the search bar moved to the top. See issue #24

**Comment by huonggiangbui** [comment]
I am interested in this issue and want to give it a try with your help. Can you assign it to me?

**Comment by xlogix** [comment]
Assigned!

**Comment by annu12340** [comment]
Can I work on this issue

**Comment by huonggiangbui** [comment]
I am not available to take this issue now. @xlogix you could assign to someone else

**Comment by pydevsg** [comment]
@annu12340 if you are willing to work , you can go ahead.
