### ISSUE TITLE
Add a landing page for the App

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-app#48]
The contributor should be able to able to put together a landing page that can show the why & how of the problem we're solving to people. It's crucial that the page looks engaging and follows good UX practices.

**Comment by annu12340** [comment]
Hi @xlogix 
So, according to this issue, you would like to add a new landing page in footsteps site telling the users what footsteps is, and how the site would help them out. Am I right?

**Comment by xlogix** [comment]
Yes, you're right.

**Comment by annu12340** [comment]
I would like to work on it

**Comment by xlogix** [comment]
Assigned!

**Comment by suraj111999** [comment]
Sir I would like to work on it

**Comment by xlogix** [comment]
Sure, you guys can collaborate together!

**Comment by suraj111999** [comment]
Thanks

**Comment by siddhishree** [comment]
Hey, I would love to contribute to this issue.

**Comment by xlogix** [comment]
Go ahead. Max = 3 for this issue.

**Comment by praveenscience** [comment]
@PSpooja I am not able to assign this to you.

**Comment by PSpooja** [comment]
I am taking this issue

**Comment by praveenscience** [comment]
Great, assigned. @PSpooja and @suraj111999 Please work together on this and let's see some magical landing page! 🤘🏻

**Comment by siddhishree** [comment]
@praveenscience @PSpooja I think there is some miscommunication as I was supposed to be working on this

**Comment by praveenscience** [comment]
@suraj111999 What's happening?

**Comment by praveenscience** [comment]
@siddhishree Let's talk with @suraj111999 in the channel.

**Comment by xlogix** [comment]
Whoever is still interested to work on this issue, please reply here within the next 24 hours. I only wanted to assign a maximum of three people to this issue.

**Comment by siddhishree** [comment]
Working on it.

**Comment by abha11** [comment]
Hey, I would like to work on this issue.

**Comment by xlogix** [comment]
Thank you all for your contributions. We have a good landing page setup. Feel free to add any changes to the page if you feel we need it. Raise an issue!
