### ISSUE TITLE
Fix Type Error while loading User Public Page

### ISSUE THREAD

**Issue by R3l3ntl3ss** [fnplus/footsteps-app#50]
There is a Type Error while loading the user's Public Page at `https://footsteps.dev/user/<username>`
Example [https://footsteps.dev/user/dev](https://footsteps.dev/user/dev)

![Screenshot from 2020-03-01 10-46-50](https://user-images.githubusercontent.com/23451923/75620114-945e5700-5baa-11ea-9035-4e68089173d5.png)

**Comment by prajwal714** [comment]
I would like to take this issue.

**Comment by xlogix** [comment]
Assigned!
