### ISSUE TITLE
Add 'Mark as Done' icon on a Footstep

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-app#52]
We're working on adding a progress bar on a learning path. A progress bar can only 'progress' if the user is able to select the Footstep(s) and mark them as 'done'.

Refer to issue #17

**Comment by Samriddhi25** [comment]
I would like to take this task

**Comment by xlogix** [comment]
Assigned!

**Comment by aditianshu** [comment]
@xlogix this issue is necessary for another issue I'm assigned for, the issue has been dormant for long, can I be assigned if it's okay?

**Comment by xlogix** [comment]
Go ahead!

**Comment by aditianshu** [comment]
![image](https://user-images.githubusercontent.com/55697933/79721520-1c85f080-8300-11ea-8ddf-49012b6292b4.png)

@xlogix is this okay?

**Comment by xlogix** [comment]
Can we add a Fab on the side so this button doesn't take unnecessary space?

**Comment by aditianshu** [comment]
Okay, I'll check it out.

**Comment by aditianshu** [comment]
![image](https://user-images.githubusercontent.com/55697933/79784724-4a9b1d00-8360-11ea-9eae-27039a02cb21.png)

FAB wasn't available in the design module, I've added a button.

**Comment by xlogix** [comment]
Alright. maybe you can make it bigger and keep it on the right? Make it half-way on the card and half outside... maybe that'll look good

**Comment by aditianshu** [comment]
@xlogix done!
Made a PR.

**Comment by xlogix** [comment]
Can you put up a screenshot?

**Comment by aditianshu** [comment]
![image](https://user-images.githubusercontent.com/55697933/79818134-aab3b280-83a4-11ea-806e-4397bde8fd77.png)
@xlogix 
The tick looked out of place when below the arrow of visit website therefore it's in the extreme right. I reduced the size of the description a bit, as I had to fit it.

**Comment by aditianshu** [comment]
Also, I had an issue with the checks, could you help me with it?😅

**Comment by xlogix** [comment]
Let's move it to the top right?

**Comment by R3l3ntl3ss** [comment]
Moving it to somewhere in the top sounds good to me.

**Comment by aditianshu** [comment]
![image](https://user-images.githubusercontent.com/55697933/80017740-ab5a5f00-84f2-11ea-9dcb-aa09add1b1b9.png)

@xlogix how about this? Next to the title. Looks neat.

**Comment by xlogix** [comment]
Alright go-ahead. Can't think of anything better right now

**Comment by xlogix** [comment]
Can you just add a green background to the icon?
![image (1)](https://user-images.githubusercontent.com/16256275/80167072-18f2b200-85fd-11ea-92b2-bf28bb446bd5.png)

Also, convert all the shadows in the page to:
- Blur: 17px
- Color: #222222
- Opacity: 9% or 11%

**Comment by aditianshu** [comment]
![image](https://user-images.githubusercontent.com/55697933/80187239-e791da80-862c-11ea-87d3-03a406e56d5d.png)

Added the background and modified the shadows

**Comment by xlogix** [comment]
Awesome @aditianshu. Have you pushed the changes in the PR you raised?

**Comment by aditianshu** [comment]
I've pushed the changes in the PR
