### ISSUE TITLE
The footer disappears once the user logs in  

### ISSUE THREAD

**Issue by R3l3ntl3ss** [fnplus/footsteps-app#53]
![Footsteps   Community-made 🧑_🤝_🧑learning paths](https://user-images.githubusercontent.com/23451923/75620458-49930e00-5baf-11ea-8dac-cd1a22f0dc31.png)

**Comment by prajwal714** [comment]
I would like to work on this issue for GSSOC'20

**Comment by xlogix** [comment]
That is by design! I removed the component after the user logs in. That is not to say that we don't need the footer... But at its current state, we can something more with the footer instead of just showing thee privacy policy and terms of service.

**Comment by xlogix** [comment]
@prajwal714 Sorry but can you take up any other issue? Feel free to add more issues if you catch any bugs/features.
