### ISSUE TITLE
Case Insensitive Searching issue

### ISSUE THREAD

**Issue by prajwal714** [fnplus/footsteps-app#55]
If I search a path 'React' it shows me the results, but in case of all small case it return nothing.

![Screenshot from 2020-03-01 12-54-52](https://user-images.githubusercontent.com/30700921/75621622-afd25d80-5bbc-11ea-98e1-915d05887afe.png)
![Screenshot from 2020-03-01 12-55-13](https://user-images.githubusercontent.com/30700921/75621645-e019fc00-5bbc-11ea-926c-81493646326f.png)

**Comment by xlogix** [comment]
Thanks for reporting this issue @prajwal714!

**Comment by prajwal714** [comment]
I'll be working of this issue.

**Comment by prajwal714** [comment]
The issue was limited to my system. @xlogix kindly close this issue.
