### ISSUE TITLE
Design a new 404 Page

### ISSUE THREAD

**Issue by prajwal714** [fnplus/footsteps-app#56]
![Screenshot from 2020-03-01 13-28-43](https://user-images.githubusercontent.com/30700921/75621934-bd89e200-5bc0-11ea-8f39-e298b075cdf7.png)

**Comment by xlogix** [comment]
It does exist! You can try pinging the same URL on the main website. The page you're seeing is the default 404 page.

But you can help out in designing a new interactive 404 page. Checkout Dribble for inspirations.

**Comment by xlogix** [comment]
Let me know if you're up for designing a better 404 page.

**Comment by prajwal714** [comment]
Yeah Sure I'll design it.

**Comment by xlogix** [comment]
Assigned!

**Comment by prajwal714** [comment]
Anyone else who is interested in this issue can work.

**Comment by FrozenGirl-spd** [comment]
I would like to work on this issue. Can i please?

**Comment by xlogix** [comment]
Assigned!

**Comment by PSpooja** [comment]
I want to work in this issue. Please assign me

**Comment by dipanshuraz** [comment]
I have a design for  404 page,  assign me for this issue @xlogix

**Comment by praveenscience** [comment]
Reassigning this to @PSpooja...

**Comment by FrozenGirl-spd** [comment]
I have worked on the issue. I have created a PR. 
404page added #76
Please review it mentors.
@xlogix  @praveenscience

**Comment by praveenscience** [comment]
@FrozenGirl-spd Left some review comments. I am not sure if that works, I am sorry. You need to update your Gatsby and make sure a URL like https://deploy-preview-76--footsteps-app.netlify.com/dlskjfsdlkfj has your screen.

**Comment by PSpooja** [comment]
![Screenshot from 2020-03-03 03-04-00](https://user-images.githubusercontent.com/20374176/76084015-f9fc7a00-5fd4-11ea-8dec-63591a466425.png)

**Comment by PSpooja** [comment]
@xlogix  and @praveenscience , this design is okay or not?

**Comment by xlogix** [comment]
It looks good Pooja! My suggestion would be to pick something that shows people/path not found as this would resonate with the project and provide a better UX

**Comment by PSpooja** [comment]
okay @xlogix

**Comment by xlogix** [comment]
@PSpooja Take a look at these: [Webro](https://woobro.design/browse) and [Icons8](https://icons8.com/ouch/subject/page-not-found-1)

**Comment by PSpooja** [comment]
Yeah i was searching something like this :) thanks @xlogix

**Comment by xlogix** [comment]
Thanks, everyone! I'm closing this issue now since @annu12340 sent a PR
