### ISSUE TITLE
Learning Paths are not showing up on the User's Public Page

### ISSUE THREAD

**Issue by R3l3ntl3ss** [fnplus/footsteps-app#61]
The Public profile of the user needs to show the learning paths that they have created. Right now it only shows their profile info.

**Comment by prajwal714** [comment]
I'll work on this issue @R3l3ntl3ss

**Comment by xlogix** [comment]
I thought these were showing on the public profile @prajwal714

**Comment by prajwal714** [comment]
only the number of learning paths is shown.

**Comment by xlogix** [comment]
That I could see in the screenshot. I was asking about the paths themselves. Anyways, go ahead with this.

**Comment by prajwal714** [comment]
Created a new component for Public Page Paths, fixed some CSS issues. It's working fine now. 
![Screenshot from 2020-03-02 13-36-42](https://user-images.githubusercontent.com/30700921/75656998-40776f00-5c8b-11ea-8086-3fde0309e289.png)
![Screenshot from 2020-03-02 13-36-59](https://user-images.githubusercontent.com/30700921/75657045-5a18b680-5c8b-11ea-8190-8414616b29a8.png)
PS: can you label the bug as medium, I had to change a bunch of files in components and CSS files for testing and it took effort.  Suggest any changes if any. Thanks @xlogix .

**Comment by xlogix** [comment]
Sure, I will update the label. But, can you make sure to only show paths which don't have 'isPrivate' flag in them? Let me know if it's possible for you.

**Comment by prajwal714** [comment]
Yes i am working on that as of now. the idea is to add a field isPrivate and set it while creating a new path, the paths with the field true will be filtered out in case of any query or searching and will we only visible to the creator. Let me know if the idea is feasible.

**Comment by xlogix** [comment]
Yeah, just add the field of the DB and make sure you're checking the field value while displaying the paths. We can work on adding a switch button or something else in the UI (while creating a new path) in another pull request.

**Comment by prajwal714** [comment]
We can close the issue as of now. @xlogix

**Comment by xlogix** [comment]
Yup! Closed.
