### ISSUE TITLE
Fix SEO of the publicProfile page

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-app#65]
The Search Engine Optimisation for the public profile page needs to be updated. Apart from adding usual UTF tags, favicons, etc. The title and description of the page should be dynamic. For example, the title can be: "Walk in the footsteps of {FirstName}'" The description can be: "{FirstName} has made learning paths using FootstepsApp. Follow {FirstName} and learn the way he recommends it"

It is open to your imagination. I'm open to more ideas.

**Comment by Xtremilicious** [comment]
Would like to work on this!

**Comment by xlogix** [comment]
Assigned!
