### ISSUE TITLE
Splash Screen for Flutter App

### ISSUE THREAD

**Issue by Yashank18** [fnplus/footsteps-app#70]
I will like to start working on a flutter app with the splash screen.
@xlogix

**Comment by xlogix** [comment]
Can we add issues related to Flutter App in the Flutter repo? I'll talk to the organizers to add the repo in the point tracking system.

**Comment by Yashank18** [comment]
Okay Sure

**Comment by xlogix** [comment]
https://github.com/fnplus/footsteps-flutter-app

**Comment by xlogix** [comment]
You can add the initial codebase right now. I've messaged the GSSoC team
