### ISSUE TITLE
Write a Validator function to validate the Github, Linked, facebook links

### ISSUE THREAD

**Issue by prajwal714** [fnplus/footsteps-app#71]
Currently the links entered aren't verified if they exist or not. Write a Validator function and in the settings Page check whenever a person enters his/her Social Media link.

**Comment by imrishabh18** [comment]
Hey, assign me this issue i can work on this.

**Comment by ashishnagpal2498** [comment]
I would like to work on this issue.

**Comment by xlogix** [comment]
Assigning it to Rishabh as he requested first. Hope you understand @ashishnagpal2498

**Comment by Akansha2202** [comment]
Please assign me this

**Comment by 991rajat** [comment]
Is regex is needed or should we ping it to get a response?

**Comment by xlogix** [comment]
just need to validate. And I think this issue is resolved.
