### ISSUE TITLE
Add a button/lcon to preview the public profile from profile page

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-app#74]
The public profile page is visible at https://www.footsteps.dev/user/user-name

**Comment by SubCoder1** [comment]
I am interested to take up this issue @xlogix

**Comment by xlogix** [comment]
Assigned!

**Comment by Adyasha8105** [comment]
Can you assign this task to me @xlogix ?

**Comment by xlogix** [comment]
Assigned!

**Comment by Adyasha8105** [comment]
@xlogix please assign me again it is my fault?

**Comment by xlogix** [comment]
Looks like you accidentally removed your assignment. I've assigned you back.

**Comment by Adyasha8105** [comment]
Actually I can't ABLE TO OPEN TH SITE.

**Comment by xlogix** [comment]
Do a npm install & try again. Ping me on Slack.

**Comment by arpitasahakundu** [comment]
I want to take up this issue

**Comment by NVS16** [comment]
I am interested in working on this issue if it can be taken up?

**Comment by xlogix** [comment]
The issue is closed! Thank you for taking the time to think/work on this project. Unfortunately, someone else was already working on it. You can take up a new issue @NVS16
