### ISSUE TITLE
Adding regex for the text fields in the signup page.

### ISSUE THREAD

**Issue by imrishabh18** [fnplus/footsteps-app#79]

**Comment by imrishabh18** [comment]
Working on this.

**Comment by praveenscience** [comment]
@imrishabh18 The GitHub or Twitter URLs do not allow me if I have a valid account with `_` character. For example: https://twitter.com/hello_world is a valid twitter account and it's not accepting.

**Comment by xlogix** [comment]
Yes! Mentioned the correct regex to use [here](https://github.com/fnplus/footsteps-app/pull/78)

**Comment by Kuljeet-123** [comment]
@xlogix can I work on this issue.

**Comment by shreyakapoor08** [comment]
Can i work on this?

**Comment by xlogix** [comment]
Assigned
