### ISSUE TITLE
The website not working after login with github

### ISSUE THREAD

**Issue by maxloh** [fnplus/footsteps-app#83]
The page become blank after a few seconds and the following error message is printed to the console

```
TypeError: Cannot read property 'split' of null
    at o.a.componentDidMount (signUpFlow.js:36)
    at ys (react-dom.production.min.js:6372)
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Gi (react-dom.production.min.js:2842)
    at bs (react-dom.production.min.js:6153)
    at os (react-dom.production.min.js:5456)
    at react-dom.production.min.js:2877
    at t.unstable_runWithPriority (scheduler.production.min.js:274)
    at Gi (react-dom.production.min.js:2842)
    at Yi (react-dom.production.min.js:2872)
fc @ commons-2acae78f2a3b97d5654e.js:1
```

![image](https://user-images.githubusercontent.com/35831069/76144642-81251d00-60bd-11ea-9ff5-47be4994d6b5.png)

**Comment by xlogix** [comment]
I just tested it now. It seems to be working fine on my end. Can you try once again? Maybe it was a one-time error.

**Comment by maxloh** [comment]
> I just tested it now. It seems to be working fine on my end. Can you try once again? Maybe it was a one-time error.

No. The bug still exists.

Tried to open the website in Chrome 80.0.3987.132 and Chrome Dev 82.0.4077.0 with all extensions disabled, no luck.

**Comment by xlogix** [comment]
Oh? Can you share your email-id? You can mail me here: abhishekuniyal09@gmail.com

**Comment by xlogix** [comment]
@R3l3ntl3ss @praveenscience Can you guys check this out?

**Comment by maxloh** [comment]
> Oh? Can you share your email-id? You can mail me here: [abhishekuniyal09@gmail.com](mailto:abhishekuniyal09@gmail.com)

I am logging in with this GitHub account.

Are you meaning the email associated with this GitHub account?

**Comment by xlogix** [comment]
> I face issues when logging in with this GitHub account. Are you meaning the email associated with this GitHub account?
Yes, the email associated with that account.

It's weird that it's happening with that specific account. Let me try upgrading Firebase as well.

**Comment by xlogix** [comment]
Hey, I've upgraded the dependencies. Try it now

**Comment by praveenscience** [comment]
I'll take this up and try to find a fix.

**Comment by xlogix** [comment]
@maxloh The bug seems to be because of 'none' value in the user's name. So, it's probably happening because you may have an empty value for name.
<img width="785" alt="Screenshot 2020-03-09 at 7 40 35 AM" src="https://user-images.githubusercontent.com/16256275/76177227-8b3c3e00-61d9-11ea-9cea-45f518466bc1.png">

**Comment by maxloh** [comment]
> @maxloh The bug seems to be because of 'none' value in the user's name. So, it's probably happening because you may not have set a full name for your Github account
> 
> Here's what's happening at line 36
> <img alt="Screenshot 2020-03-09 at 7 40 35 AM" width="785" src="https://user-images.githubusercontent.com/16256275/76177227-8b3c3e00-61d9-11ea-9cea-45f518466bc1.png">

Yap. I can confirm that I did not set a full name for this GitHub account.

But after I set a full name, revoke Footsteps App's OAuth access, authorize it again, and try to login in a incognito window, the bug still exists.

**Comment by xlogix** [comment]
> > @maxloh The bug seems to be because of 'none' value in the user's name. So, it's probably happening because you may not have set a full name for your Github account
> > Here's what's happening at line 36
> > <img alt="Screenshot 2020-03-09 at 7 40 35 AM" width="785" src="https://user-images.githubusercontent.com/16256275/76177227-8b3c3e00-61d9-11ea-9cea-45f518466bc1.png">
> 
> Yap. I can confirm that I did not set a full name for this GitHub account.
> 
> But after I set a full name, revoke Footsteps App's OAuth access, authorize it again, and try to login in an incognito window, the bug still exists.

Let me try removing the user from Firebase as well. Can you mail or paste your Github account email-id?

**Comment by maxloh** [comment]
> > > @maxloh The bug seems to be because of 'none' value in the user's name. So, it's probably happening because you may not have set a full name for your Github account
> > > Here's what's happening at line 36
> > > <img alt="Screenshot 2020-03-09 at 7 40 35 AM" width="785" src="https://user-images.githubusercontent.com/16256275/76177227-8b3c3e00-61d9-11ea-9cea-45f518466bc1.png">
> > 
> > 
> > Yap. I can confirm that I did not set a full name for this GitHub account.
> > But after I set a full name, revoke Footsteps App's OAuth access, authorize it again, and try to login in an incognito window, the bug still exists.
> 
> Let me try removing the user from Firebase as well. Can you mail or paste your Github account email-id?

Thx. I have emailed you the email addresses associated with my account.

The email title was "Email address for GitHub issue #83".

**Comment by maxloh** [comment]
I am able to use the app now. Feel free to close this issue.

Thanks for your help :)

**Comment by xlogix** [comment]
Thanks for the feedback. @praveenscience Can you add the send a PR to add a check for empty names?

**Comment by praveenscience** [comment]
@xlogix It's done! #88
