### ISSUE TITLE
Migrate 'react-tag-input' dependency to 'react-tag-autocomplete' & add basic autocomplete suggestions

### ISSUE THREAD

**Issue by xlogix** [fnplus/footsteps-app#86]
React Tag Input dependency is used in the on-boarding process of the app when the user enters his/her skills. This process can take a while since there are no auto-complete suggestions in the tags. We should add basic complete options for skills.

Link to the package: https://www.npmjs.com/package/react-tag-autocomplete

Make sure to remove peer dependencies of react-tag-input as well.

**Comment by imrishabh18** [comment]
Hey, i will work on this

**Comment by xlogix** [comment]
Assigned!

**Comment by imrishabh18** [comment]
@xlogix I have added the react-tag-autocomplete dependency and removed the react-tag-input dependency. Do i need to add the tags and suggestion thing also ?

**Comment by xlogix** [comment]
Did you remove the subdependencies of the react-tag too?

Yes, find a list of most popular skills in tech (at least) to add.

**Comment by imrishabh18** [comment]
What are the sub-dependencies of the react-tag ?

**Comment by xlogix** [comment]
Here you go: https://github.com/prakhar1989/react-tags

**Comment by xlogix** [comment]
@imrishabh18 Any updates?

**Comment by imrishabh18** [comment]
@xlogix Hey, react-tags dependecies are these
 
react: ^16.3.1,
react-dnd: ^5.0.0
react-dnd-html5-backend: ^3.0.2
react-dom": ^16.3.1

If i remove them won't it affect our react app ? as there is react also included.

**Comment by xlogix** [comment]
You have to remove the ones beside react & react-dom.

**Comment by imrishabh18** [comment]
When i am commit the changes it still fails the eslint check for the regex thing and i can't push the changes. What should i do ?

**Comment by xlogix** [comment]
You can add the skip/ignore flag & try to commit.

**Comment by xlogix** [comment]
@imrishabh18 Are you still interested in completing this?

**Comment by imrishabh18** [comment]
No, i will pass.

**Comment by xlogix** [comment]
Okay...

**Comment by shreyakapoor08** [comment]
can i do this ?

**Comment by xlogix** [comment]
Sure
