### ISSUE TITLE
Fix controlled components on Sign Up screen

### ISSUE THREAD

**Issue by praveenscience** [fnplus/footsteps-app#88]
When you try to sign up for the first time by giving the first name and last name, here's what is happening.

![image](https://user-images.githubusercontent.com/1830380/76166381-00662f80-6156-11ea-8ff3-9f5de67efff1.png)

**Comment by GianCastle** [comment]
Hi,

Can I take this issue?

**Comment by xlogix** [comment]
@praveenscience working on it?

**Comment by praveenscience** [comment]
@GianCastle It's done. Thanks for offering plus if you're looking for if this is GSSoC issue, this isn't.

**Comment by GianCastle** [comment]
I saw this project a 2 weeks ago, I like the idea and I'm interested in working on it as a side-project. Didn't know it was part of GSSoC, awesome!

> @GianCastle It's done. Thanks for offering plus if you're looking for if this is GSSoC issue, this isn't.
